ALTER TABLE  `vote_usr` CHANGE  `pic`  `pic` VARCHAR( 128 ) NULL DEFAULT NULL , CHANGE  `usr`  `usr` VARCHAR( 128 ) NULL DEFAULT NULL;
ALTER TABLE  `vote_usr` CHANGE  `pic`  `pic` VARCHAR( 128 ) NULL DEFAULT NULL , CHANGE  `ip`  `ip` VARCHAR( 15 ) NULL DEFAULT NULL;
